### ISSUE TITLE
Outputting approximate weeks in `distance-in-words`.

### ISSUE THREAD

**Issue by rome-user** [lambdaisland/deja-fu#11]
Hi. Is there interest in adding this sort of functionality to the `distance-in-words` function? It would be very useful for my use cases. I'd be happy to eventually send a PR to add this feature.

**Comment by alysbrooks** [comment]
I think that definitely could be useful. Would weeks always be displayed (above one week ago)? Or were you thinking it would be an option? It's a port of ActiveSupport functionality, so it might be good to follow its API.

**Comment by rome-user** [comment]
Right now I am interested in patching this function so that the range "7 days - 21 days" is represented with weeks (specifically, "1 week - 3 weeks"). Then 22 - 30 days may be "about 1 month".

I'm open to hearing different ideas for this.
